# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1"

package:
  name: healib
  version: ${{ version }}

source:
  path: ./src

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    # - if: unix
    #   then:
    #     - make

about:
  homepage: https://heasarc.gsfc.nasa.gov
  #license: healib
  #license_file: LICENSE
  summary: base tool for heasoft conda packages
  description: |
    basic conda package template.
  documentation: https://heasarc.gsfc.nasa.gov/docs/
  repository: https://github.com/heasoft/healib