
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data
  version: 6.36
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/.testing/source/${{ name }}-${{ version }}.tar.gz
  sha256: ea2323b40826e701b80c17f42398e58084a1d5761b3e2b1ac2871b3b7f9a36ad

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv Xspec/src/spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
  summary: Main xspec data
  description: |
    Main xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
