
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data
  version: 6.34
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: 5d24f93481be2b294c7f114ee43603739cabbe0fe327acd5b8d0a5744af9c8bf

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/

tests:
  - package_contents:
      files:
        - ${{ hea_subdir }}/spectral/modelData/Bearden.fits
        - ${{ hea_subdir }}/spectral/modelData/mekal.mod

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
  summary: Main xspec data
  description: |
    Main xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/