
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data
  version: 12.14.1
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: 180cdca9f8ec2a54f960782f152ce03e394bf78be8a8d623df0e97d381025571

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/

tests:
  - package_contents:
      files:
        - ${{ hea_subdir }}/spectral/modelData/Bearden.fits
        - ${{ hea_subdir }}/spectral/modelData/mekal.fits

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
  summary: Main xspec data
  description: |
    Main xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/