
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data
  version: 6.35
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: 6828b6c7435c3dfbb609b562b282d1992bf6cf02e1975c2f2bb4d4753818a7b3

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv Xspec/src/spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/

tests:
  - package_contents:
      files:
        - ${{ hea_subdir }}/spectral/modelData/Bearden.fits
        - ${{ hea_subdir }}/spectral/modelData/mekal.mod

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
  summary: Main xspec data
  description: |
    Main xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/