
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data
  version: 6.35
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: 455e4855223e1f2014076c3d860de2975798dd7e63a4cf74f561d433fd1eaa29

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv Xspec/src/spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/

tests:
  - package_contents:
      files:
        - ${{ hea_subdir }}/spectral/modelData/Bearden.fits
        - ${{ hea_subdir }}/spectral/modelData/mekal.mod

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/
  summary: Main xspec data
  description: |
    Main xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/