# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft
  version: 6.36

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  #sha256: 53d91083195ddad7f19260ba6dbeebc01d96802f7e0e7db9d17e950eb4e7b4f9
  url: https://heasarc.gsfc.nasa.gov/FTP/software/irby/conda/${{ name }}-${{ version }}.tar.gz
  sha256: 90e7e41850c719c84093c9fb8850f91ca9bff02a1c0222ad99dbdce26d640c5a
  patches:
    - configures_opt.patch
    - tcltk_Makefile.patch
    - pgplot_makefiles.patch
    - xspec.patch
    - xspec2.patch
    - zlib_makefiles.patch
    - python_makefiles.patch
    - itk_configure.patch
    - iwidgets_configure.patch
    - tix_configure.patch
    - if: osx
      then:
      - configures.patch
      - pgplot_makefiles_osx.patch
    - if: linux
      then:
      - xpa.patch
      - mktclapp.patch
      - fv_makefile.patch
      - fv_unix.patch
    - perl_config.patch
    - fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fftw
    - fgsl
    - gsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux
      then:
        - kernel-headers_linux-64 = 3.10.0
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fftw
    - fgsl
    - gsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux or (osx and not arm64)
      then:
        - lynx

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
