# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft
  version: develop

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/irby/conda/.test/${{ name }}-${{ version }}.tar.gz
  sha256: 774bfff9fec2d76954a7280719d57ab7974f30bda8ccf0e700aea0191346a3ad
  patches:
    - tcltk_Makefile.patch
    - pgplot_makefiles.patch
    - xspec.patch
    - xspec2.patch
    - zlib_makefiles.patch
    - python_makefiles.patch
    - itk_configure.patch
    - iwidgets_configure.patch
    - tix_configure.patch
    - if: osx
      then:
      - configures.patch
      - pgplot_makefiles_osx.patch
    - if: linux
      then:
      - fv_makefile.patch
      - fv_unix.patch
    - perl_config.patch
    - fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fftw
    - fgsl
    - gsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux
      then:
        - kernel-headers_linux-64 = 3.10.0
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fftw
    - fgsl
    - gsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux or (osx and not arm64)
      then:
        - lynx

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
