# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft
  version: develop

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/irby/conda/.test/${{ name }}-${{ version }}.tar.gz
  sha256: d42170006857abed358bf4a16abcc153f4221c9e158485f1ea6000127b631d11
  patches:
    - tcltk_Makefile.patch
    - pgplot_makefiles.patch
    - xspec.patch
    - xspec2.patch
    - zlib_makefiles.patch
    - python_makefiles.patch
    - itk_configure.patch
    - iwidgets_configure.patch
    - tix_configure.patch
    - if: osx
      then:
      - configures.patch
      - pgplot_makefiles_osx.patch
    - if: linux
      then:
      - fv_makefile.patch
      - fv_unix.patch
    - perl_config.patch
    - fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux and not aarch64
      then:
        - kernel-headers_linux-64 = 3.10.0
    - if: linux and aarch64
      then:
        - kernel-headers_linux-aarch64 = 3.10.0
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: (linux and not aarch64) or (osx and not arm64)
      then:
        - lynx

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
