# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft
  version: 6.35.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: b3db0ce965a37336428e99e80cdd0eeef0d904a95ec2ab377e26673b4976e61f
  patches:
    - gsl_configure.patch
    - tcltk_Makefile.patch
    - pgplot_makefiles.patch
    - xspec.patch
    - zlib_makefiles.patch
    - python_makefiles.patch
    - heauninit.patch
    - if: osx
      then:
      - configures.patch
      - wcslib_tclrl.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fgsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fgsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux or (osx and not arm64)
      then:
        - lynx

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
