# yaml-language-server: $schema=../../../schema.json

context:
  name: cfitsio
  version: 4.5.0
  # note that this is the sha for the unzipped file. The download script
  # seem to unzip the file. Is this an issue with the way the heasarc server
  # serve the files? or is it an issue with rattler-build?
  sha256: 81db33b99b9db1af539cd9ce0c778f75ca5d3f9c448095262e5e1b5fb8e6effa

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/${{ name }}-${{ version }}.tar.gz
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software/${{ name }}-${{ version }}.tar
  sha256: ${{ sha256 }}

build:
  number: 0

requirements:
  build:
    - libtool
    - autoconf
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    - make
  host:
    - zlib
    - bzip2
    - libcurl
  run_exports:
    - ${{ pin_subpackage('cfitsio', upper_bound='x.x.x') }}

tests:
  - script:
    - fitsverify -h

about:
  homepage: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  #license: LicenseRef-fitsio
  #license_file: LICENSE
  summary: A library for reading and writing FITS files
  description: |
    CFITSIO is a library of C and Fortran subroutines for reading and writing
    data files in FITS (Flexible Image Transport System) data format. CFITSIO
    provides simple high-level routines for reading and writing FITS files that
    insulate the programmer from the internal complexities of the FITS format.
    CFITSIO also provides many advanced features for manipulating and filtering
    the information in FITS files.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html
