# yaml-language-server: $schema=../../../schema.json

context:
  name: cfitsio
  version: 4.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ./src/${{ name }}-${{ version }}.tar.gz
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/${{ name }}-${{ version }}.tar.gz
  #sha256: e4854fc3365c1462e493aa586bfaa2f3d0bb8c20b75a524955db64c27427ce09

build:
  number: 0

requirements:
  build:
    - libtool
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    #- ${{ stdlib("c") }}
    - make
  # host:
  #   - libcurl
  #   - bzip2
  #   - zlib
  # run:
  #   - libcurl
  #   - bzip2
  #   - zlib

# tests:
#   - package_contents:
#       include:
#         - ${PREFIX}/lib/libcfitsio{{ SHLIB_EXT }} 
about:
  homepage: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  #license: LicenseRef-fitsio
  #license_file: LICENSE
  summary: A library for reading and writing FITS files
  description: |
    CFITSIO is a library of C and Fortran subroutines for reading and writing
    data files in FITS (Flexible Image Transport System) data format. CFITSIO
    provides simple high-level routines for reading and writing FITS files that
    insulate the programmer from the internal complexities of the FITS format.
    CFITSIO also provides many advanced features for manipulating and filtering
    the information in FITS files.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html
  #repository: https://github.com/xtensor-stack/xtensor