
context:
  name: CCfits
  version: 2.6
  # note that this is the sha for the unzipped file. The download script
  # seem to unzip the file. Is this an issue with the way the heasarc server
  # serve the files? or is it an issue with rattler-build?
  sha256: c8395e80379df4e2a63b0890166fb47be4b96dff977214e7ed10ea9d3e9e9a9e

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/${{ name }}-${{ version }}.tar.gz
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software/${{ name }}-${{ version }}.tar
  sha256: ${{ sha256 }}

build:
  number: 0

requirements:
  build:
    - automake
    - ${{ compiler('cxx') }}
  host:
    - cfitsio > 4.4.1, <= 4.5.0


about:
  homepage: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  #license: LicenseRef-fitsio
  #license_file: LICENSE
  summary: C++ wrappers for cfitsio
  description: |
    C++ wrappers for cfitsio.
  documentation: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
