

# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data-extra
  version: 6.34
  hea_subdir: heasoft

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: d366e893cb24a92bb602c9eb99d1492ae39737b94d33683c2b6ab9a208c75948

build:
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/${{ hea_subdir }}/spectral/modelData
      mv spectral/modelData/* $PREFIX/${{ hea_subdir }}/spectral/modelData/

tests:
  - package_contents:
      files:
        - ${{ hea_subdir }}/spectral/modelData/xillver-a-Ec3.fits

about:
  homepage: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  summary: Extra xspec data
  description: |
    Extra xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html