
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-data-extra
  version: 12.14.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}
source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: 4ea153bdf3c5ff91c7ab3510c581f948058da22fe43bc1bb226bd53a2c258890
build:
  number: 0
  noarch: generic
  script:
    content: |
      mkdir -p $PREFIX/spectral/modelData
      mv spectral/modelData/* $PREFIX/spectral/modelData/

about:
  homepage: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  #license: LicenseRef-fitsio
  #license_file: LICENSE
  summary: Extra xspec data
  description: |
    Extra xspec data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html