# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec
  version: 12.15.1
  hea_version: 6.37

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/.testing/source/${{ name }}-${{ version }}.tar.gz
  sha256: 861b22b1f3ce7f456f0c422ed91ba657d56376be99e5e2b4d1e4e1f677ab062c
  #path: /local/data/karpuz1/birby/conda/heasoft
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/perl_config_heacore.patch
    - ../heasoft/python_makefiles_heacore.patch
    - ../heasoft/python_makefiles_xspec.patch
    - if: osx
      then:
      - ../heasoft/pgplot_makemake_osx.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fgsl
    - numpy
    - if: linux
      then:
        - kernel-headers_linux-64 = 3.10.0
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fgsl
    - numpy


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
  #license_file: LICENSE
  summary: Xspec
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
