# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec
  version: 12.15.1
  hea_version: 6.36

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/heasoft-${{ hea_version }}.tar.gz
  sha256: 53d91083195ddad7f19260ba6dbeebc01d96802f7e0e7db9d17e950eb4e7b4f9
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/pgplot_makefiles.patch
    - ../heasoft/xspec.patch
    - ../heasoft/xspec2.patch
    - ../heasoft/zlib_makefiles.patch
    - ../heasoft/python_makefiles.patch
    - ../heasoft/itk_configure.patch
    - ../heasoft/iwidgets_configure.patch
    - ../heasoft/tix_configure.patch
    - if: osx
      then:
      - ../heasoft/configures.patch
      - ../heasoft/pgplot_makefiles_osx.patch
    - ../heasoft/perl_config.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fgsl
    - numpy
    - if: linux
      then:
        - kernel-headers_linux-64 = 3.10.0
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fgsl
    - numpy


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
  #license_file: LICENSE
  summary: Xspec
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
