# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec
  version: 12.15.0
  hea_version: 6.35

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/heasoft-${{ hea_version }}.tar.gz
  sha256: 96c8dc74cbd26a45fab4f615e1a605f0c3d5ce35c49668f6198870cad1c92bc0
  patches:
    - ../heasoft/gsl_configure.patch
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/pgplot_makefiles.patch
    - ../heasoft/xspec.patch
    - ../heasoft/zlib_makefiles.patch
    - ../heasoft/python_makefiles.patch
    - if: osx
      then:
      - ../heasoft/configures.patch
      - ../heasoft/wcslib_tclrl.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
  host:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fgsl
    - numpy
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fgsl
    - numpy
    - xspec-data = ${{ hea_version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
  #license_file: LICENSE
  summary: Xspec
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
