# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-compilers
  version: 13.0.0
  cxx_version: 16.1.0
  c_version: ${{ cxx_version }}
  fortran_version: ${{ cxx_version }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}


build:
  number: 0

requirements:
  run:
    - ${{ compiler('cxx') }} = ${{ cxx_version }}
    - ${{ compiler('c') }} = ${{ c_version }}
    - ${{ compiler('fortran') }} = ${{ fortran_version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
  #license_file: LICENSE
  summary: Pack the compilers that can be used to build xspec models.
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
