# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xspec-compilers
  version: 13.0.0
  gnu_version: 16.1.0
  clang_version: 22.1.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}


build:
  number: 0

requirements:
  run:
    - ${{ compiler('fortran') }} = ${{ gnu_version }}
    - if: osx
      then:
      - ${{ compiler('cxx') }} = ${{ clang_version }}
      - ${{ compiler('c') }} = ${{ clang_version }}
    - if: linux
      then:
      - ${{ compiler('cxx') }} = ${{ gnu_version }}
      - ${{ compiler('c') }} = ${{ gnu_version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
  #license_file: LICENSE
  summary: Pack the compilers that can be used to build xspec models.
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/xanadu/xanadu.html
