
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xstar-data
  version: 6.35.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}
source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: a818e7ed026edc27b155042074054c377fc2998e0e496daf7814e7dd4b38c428
build:
  number: 0
  noarch: generic
  script:
    content: |
      HEA_SUBDIR=heasoft
      mkdir -p $PREFIX/$HEA_SUBDIR/refdata
      mv ftools/xstar/data/* $PREFIX/$HEA_SUBDIR/refdata/

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html
  summary: Main xstar data
  description: |
    Main xstar data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html