
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xstar-data
  version: 6.35.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}
source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: 5fa0bfd8759296c795c293aa2dbc8bb65a601c46597bb31df04759653ebd4524
build:
  number: 0
  noarch: generic
  script:
    content: |
      HEA_SUBDIR=heasoft
      mkdir -p $PREFIX/$HEA_SUBDIR/refdata
      mv ftools/xstar/data/* $PREFIX/$HEA_SUBDIR/refdata/

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html
  summary: Main xstar data
  description: |
    Main xstar data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html