
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: xstar-data
  version: 6.35.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}
source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: c9051c87c36c2bc3c5a9adc43c6d5d2529fcef05b7362fa96577a579f40698d6
build:
  number: 0
  noarch: generic
  script:
    content: |
      HEA_SUBDIR=heasoft
      mkdir -p $PREFIX/$HEA_SUBDIR/refdata
      mv ftools/xstar/data/* $PREFIX/$HEA_SUBDIR/refdata/

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html
  summary: Main xstar data
  description: |
    Main xstar data
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/xstar/xstar.html