# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: maxi
  version: 6.37

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/.testing/source/${{ name }}-${{ version }}.tar.gz
  sha256: ef943ed7af3442833a9e605bc058717c99ad89ecee43a00be2c87c587148f033
  #path: /local/data/karpuz1/birby/conda/heasoft
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/perl_config_heacore.patch
    - ../heasoft/perl_config_maxi.patch
    - ../heasoft/python_makefiles_heacore.patch
    - ../heasoft/python_makefiles_xspec.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux and not aarch64
      then:
        - kernel-headers_linux-64 = 3.10.0
    - if: linux and aarch64
      then:
        - kernel-headers_linux-aarch64 = 4.18.0
    # readline
    # cfitsio
    # wcslib
    # ape
    # attitude (atFunctions)
    # heainit
    # heaio
    # heautils
    # ahapp
    # ahgen
    # ahlog
    # heaapp
    # xspec
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: (linux and not aarch64) or (osx and not arm64)
      then:
        - lynx
    # readline
    # cfitsio
    # wcslib
    # ape
    # attitude (atFunctions)
    # heainit
    # heaio
    # heautils
    # ahapp
    # ahgen
    # ahlog
    # heaapp
    # xspec
    # cfitsio-perl
    - heagen
    - heatools
    - caltools
    - fimage
    - futils
    - heasarc
    - time

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
