# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasarc
  version: 6.37

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/.testing/source/${{ name }}-${{ version }}.tar.gz
  sha256: d0125e3a6c7e51ec97d4573b10508e8cced9c04dbf23f786caf7222e11633269
  #path: /local/data/karpuz1/birby/conda/heasoft
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/perl_config_heacore.patch
    - ../heasoft/python_makefiles_heacore.patch
    - if: osx
      then:
      - ../heasoft/pgplot_makemake_osx.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-xorgproto
    - xorg-libxcursor
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - pip
    - setuptools
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: linux and not aarch64
      then:
        - kernel-headers_linux-64 = 3.10.0
    - if: linux and aarch64
      then:
        - kernel-headers_linux-aarch64 = 4.18.0
    # readline
    # cfitsio
    # ape
    # heainit (getocctimes, gtiinvert)
    # heaio (getocctimes, gtiinvert)
    # heautils (getocctimes, gtiinvert, searchflickpix)
    # heaapp (searchflickpix, gtiinvert)
    # ahlog (searchflickpix, gtiinvert)
    # tcltk (pgplot, plt)
    # callib
    # xanlib
    # ftoolslib
    # cftoolslib
  run:
    - libcurl
    - zlib
    - libbrotlidec
    - libiconv
    - libpng
    - xorg-libx11
    - xorg-libxt
    - xorg-libxcursor
    - xorg-xorgproto
    - fftw
    - gsl
    - if: osx or (linux and not aarch64)
      then:
        - fgsl
    - perl
    - numpy
    - scipy
    - astropy-base
    - matplotlib
    - if: (linux and not aarch64) or (osx and not arm64)
      then:
        - lynx
    # readline
    # cfitsio
    # ape
    # heainit (getocctimes, gtiinvert)
    # heaio (getocctimes, gtiinvert)
    # heautils (getocctimes, gtiinvert, searchflickpix)
    # heaapp (searchflickpix, gtiinvert)
    # ahlog (searchflickpix, gtiinvert)
    # tcltk (pgplot, plt)
    # callib
    # xanlib
    # ftoolslib
    # cftoolslib
    # cfitsio-perl (pileest)
    - heasptools
    - heatools
    - futils
    - fimage
    - ximage
    # attitude (pileest, via HEAGEN.pm)
    # caltools (pileest, via HEAGEN.pm)
    # heasarc (pileest, via HEAGEN.pm)
    # time (pileest, via HEAGEN.pm)
    # qdp (pileest, via HEAGEN.pm)
    # xronos (pileest, via HEAGEN.pm)
    # xselect (pileest, via HEAGEN.pm)

about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
