name: Build Conda Package

on:
  workflow_dispatch:
  push:
    branches: ['main', 'gh']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true 
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-arm64
          - os: macos-latest
            platform: osx-64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          miniforge-version: latest        
      

      - name: Install rattler-build
        run: |
          mamba install -y rattler-build

      - name: Build Heasoft
        run: |
          cd heasoft
          rattler-build build --no-include-recipe --output-dir ../output

      - name: Upload conda package
        uses: actions/upload-artifact@v4
        with:
          name: conda-package-${{ matrix.platform }}
          path: output/
