# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft-tests
  version: 6.34

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: 493bf0af40db84d1c75a4c2880a5b427a97e2b03db1fa060aa33041aa433901f
  patches:
    - ../heasoft/gsl_configure.patch
    - ../heasoft/heainit.patch
    - ../heasoft/heaev_Makefile.patch
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/heasoftpy_install.patch
    - ../heasoft/pgplot_makefiles.patch
    - ../heasoft/xspec.patch
    - ../heasoft/zlib_makefiles.patch
    - ../heasoft/hitomi_makefiles.patch
    - ../heasoft/python_makefiles.patch
    - maxi_mxgrmfgen_test.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - if: linux
      then:
        - patchelf
  host:
    - heasoft = 6.34
  run:
    - heasoft = 6.34


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: adds unit test binaries to the core heasoft library. This is for internal testing.
  description: |
    heasoft tests.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
