# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft-tests
  version: 6.37

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/.testing/source/${{ name }}-${{ version }}.tar.gz
  sha256: 861b22b1f3ce7f456f0c422ed91ba657d56376be99e5e2b4d1e4e1f677ab062c
  #path: /local/data/karpuz1/birby/conda/heasoft
  patches:
    - ../heasoft/itk_configure.patch
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/perl_config_heacore.patch
    - ../heasoft/perl_config_tcltk_pgperl.patch
    - ../heasoft/perl_config_maxi.patch
    - ../heasoft/python_makefiles_heacore.patch
    - ../heasoft/python_makefiles_xspec.patch
    - ../heasoft/zlib_makefiles_fv.patch
    - ../heasoft/zlib_makefiles_xte.patch
    - if: osx
      then:
      - ../heasoft/pgplot_makemake_osx.patch
    - if: linux
      then:
      - ../heasoft/xpa.patch
      - ../heasoft/mktclapp.patch
      - ../heasoft/fv_makefile.patch
      - ../heasoft/fv_unix.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - heasoft = ${{ version }}
  run:
    - heasoft = ${{ version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: adds unit test binaries to the core heasoft library. This is for internal testing.
  description: |
    heasoft tests.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
