# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft-tests
  version: 6.34

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarcdev.gsfc.nasa.gov/azoghbi/software-full/${{ name }}-${{ version }}.tar
  sha256: 7929691a627e6ba74c2b9e797f248105e45a1b356a7910219e329bebaffe731d
  patches:
    - gsl_configure.patch
    - heainit.patch
    - heaev_Makefile.patch
    - tcltk_Makefile.patch
    - heasoftpy_install.patch
    - pgplot_makefiles.patch
    - xspec.patch
    - zlib_makefiles.patch
    - hitomi_makefiles.patch
    - python_makefiles.patch
    - maxi_mxgrmfgen_test.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - if: linux
      then:
        - patchelf
  host:
    - heasoft = 6.34
  run:
    - heasoft = 6.34


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: the core library of heasoft
  description: |
    xspec.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
