# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft-tests
  version: 6.37

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/irby/conda/.test/${{ name }}-${{ version }}.tar.gz
  sha256: ec5000543c190c44f3f6554231fabb3137d991e2d202950e10864362a0ca5b58
  #path: /local/data/karpuz1/birby/conda/heasoft
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/pgplot_makefiles.patch
    - ../heasoft/zlib_makefiles.patch
    - ../heasoft/python_makefiles.patch
    - ../heasoft/itk_configure.patch
    - if: osx
      then:
      - ../heasoft/pgplot_makefiles_osx.patch
    - if: linux
      then:
      - ../heasoft/xpa.patch
      - ../heasoft/mktclapp.patch
      - ../heasoft/fv_makefile.patch
      - ../heasoft/fv_unix.patch
    - ../heasoft/perl_config.patch
    - ../heasoft/fix-x11-conda.patch

build:
  number: 0

requirements:
  host:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - heasoft = ${{ version }}
  run:
    - heasoft = ${{ version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: adds unit test binaries to the core heasoft library. This is for internal testing.
  description: |
    heasoft tests.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
