# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: heasoft-tests
  version: 6.35.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/${{ name }}-${{ version }}.tar.gz
  sha256: ec9e5b69906d13e2863d9711ce96be018cb7220d73b77cbc2c945491a29428f4
  patches:
    - ../heasoft/tcltk_Makefile.patch
    - ../heasoft/pgplot_makefiles.patch
    - ../heasoft/xspec.patch
    - ../heasoft/zlib_makefiles.patch
    - ../heasoft/python_makefiles.patch
    - if: osx
      then:
        - ../heasoft/configures.patch
        - ../heasoft/wcslib_tclrl.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - pkg-config
    - if: linux
      then:
        - patchelf
  host:
    - heasoft = ${{ version }}
  run:
    - heasoft = ${{ version }}


about:
  homepage: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
  #license_file: LICENSE
  summary: adds unit test binaries to the core heasoft library. This is for internal testing.
  description: |
    heasoft tests.
  documentation: https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/
