name: Build Conda Package

on:
  workflow_dispatch:
    inputs:
        package:
          description: 'Package to build: heasoft, xspec, xspec-data etc'
          required: true
          type: string


jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true 
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-arm64
          - os: macos-latest
            platform: osx-64
    
    - name: Skip noarch packages
        if: |
          (matrix.platform == 'osx-arm64' || matrix.platform == 'osx-64') &&
          (inputs.package == 'xspec-data' || inputs.package == 'xstar-data' )
        run: |
          echo "Skipping macOS job for noarch packages: ${{ inputs.package }}"
          exit 0

    steps:
      - name: Skip noarch packages
        if: |
          (matrix.platform == 'osx-arm64' || matrix.platform == 'osx-64') &&
          (inputs.package == 'xspec-data' || inputs.package == 'xstar-data' )
        run: |
          echo "Skipping macOS job for noarch packages: ${{ inputs.package }}"
          exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: hconda
          create-args: >-
            python=3.12
            rattler-build
      - run: |
          package=${{ inputs.package }}
          echo "Building package $package"
          if ! test -d $package; then
            echo "package $package does not exist"
            exit 1
          fi 
          cd $package
          rattler-build build --no-include-recipe --output-dir ../output
          if [ $package == "heasoft" ]; then
            echo "doing heasoft-tests too"
            cd ../output/src_cache
            root=`find -type d -name 'heasoft-*'`
            ln -s ${root} ${root/heasoft/heasoft-tests}
            ln -s ${root}.tar.gz ${root/heasoft/heasoft-tests}.tar.gz
            cd ../../heasoft-tests
            rattler-build build --no-include-recipe --output-dir ../output
          fi
        shell: micromamba-shell {0}


      - name: Upload conda package
        uses: actions/upload-artifact@v4
        with:
          name: conda-package-${{ inputs.package }}-${{ matrix.platform }}
          path: output/
