name: Build Conda Package

on:
  workflow_dispatch:
    inputs:
        package:
          description: 'Package to build: heasoft, xspec, xspec-data etc'
          required: true
          type: string


jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true 
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            platform: linux-aarch64
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-arm64
          - os: macos-latest
            platform: osx-64
    name: ${{ inputs.package }} | ${{ matrix.platform }} | ${{ github.ref_name }}

    steps:
      - name: Skip noarch packages?
        id: check_skip
        run: |
          if { [ "${{ matrix.platform }}" == "osx-arm64" ] ||  [ "${{ matrix.platform }}" == "osx-64" ]; } && 
              { [ "${{ inputs.package }}" == "xspec-data" ] || [ "${{ inputs.package }}" == "xstar-data" ]; }; then
            echo "Skipping macOS job for noarch packages: ${{ inputs.package }}"
            echo "do_build=false" >> $GITHUB_OUTPUT
          else
            echo "do_build=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.check_skip.outputs.do_build == 'true'
        uses: actions/checkout@v4

      - name: prepare mamba
        uses: mamba-org/setup-micromamba@v2
        if: steps.check_skip.outputs.do_build == 'true'
        with:
          environment-name: hconda
          create-args: >-
            python=3.12
            rattler-build
      
      - name: build packages
        if: steps.check_skip.outputs.do_build == 'true'
        run: |
          # repot failures.
          set -euo pipefail
          package=${{ inputs.package }}
          echo "Building package $package"
          if ! test -d $package; then
            echo "package $package does not exist"
            exit 1
          fi 
          cd $package
          rattler-build build --no-include-recipe --target-platform ${{ matrix.platform }} --output-dir ../output
          if [ $package == "heasoft" ]; then
            echo "doing heasoft-tests too"
            cd ../output/src_cache
            # we use the same tar file
            root=`ls -d heasoft-* | grep -v tar`
            rm -rf ${root}
            ln -s ${root}.tar.gz ${root/heasoft/heasoft-tests}.tar.gz
            cd ../../heasoft-tests
            rattler-build build --no-include-recipe --target-platform ${{ matrix.platform }} --output-dir ../output
          fi
          cd ..
          rm -rf output/src_cache output/bld
        shell: micromamba-shell {0}


      - name: Upload conda package
        uses: actions/upload-artifact@v4
        if: steps.check_skip.outputs.do_build == 'true'
        with:
          name: conda-package-${{ inputs.package }}-${{ matrix.platform }}
          path: output/
